name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Match tags like v1.0.0, v2.1.3
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Pytest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r app/requirements.txt
          pip install pytest httpx

      - name: Run Tests
        run: pytest -v tests

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # Only runs if tests succeed

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.SECRET_GITHUB_PUBLISH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine Docker Tag
        id: vars
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker Image
        run: |
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${REPO_OWNER_LOWER}/web-ui:${{ steps.vars.outputs.tag }}"
          docker build --no-cache -t "$IMAGE_NAME" -f Dockerfile .
          docker push "$IMAGE_NAME"

  release:
    runs-on: ubuntu-latest
    
    # You need 'write' permission for the default GITHUB_TOKEN to push to gh-pages:
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-permissions
    permissions:
      contents: write

    steps:
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history so chart-releaser can detect tags, etc.

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          # 'charts_dir' is where your chart subfolders live:
          charts_dir: 'helm'

#  helm:
#    name: Helm Lint and Package
#    runs-on: ubuntu-22.04
#    needs: build-and-push
#
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v4
#
#      - name: Install Helm
#        uses: azure/setup-helm@v3
#        with:
#          version: v3.12.3
#
#      - name: Helm Lint
#        run: helm lint ./helm/web-ui
#
#      - name: Helm Package
#        run: |
#          helm package ./helm/web-ui --destination ./helm/output
#          ls -l ./helm/output
#
#      - name: Upload Packaged Chart
#        uses: actions/upload-artifact@v3
#        with:
#          name: web-ui-chart
#          path: ./helm/output

